#!/bin/bash
[ -z $1 ] && echo "need device" && exit 1
mkdir changeset
rm -f replay.log
while read -r line; do
    if [[ $line =~ EXIT ]] ; then
        exit 0
    fi

    if [[ $line =~ REPLAY ]] ; then
        echo $line >> replay.log
        SECTOR=$(echo $line | cut -d ':' -f 2)
        SIZE=$(echo $line | cut -d ':' -f 3)
        echo "Will need to replay sector $SECTOR ($SIZE) bytes"
        UUID=$(cat /proc/sys/kernel/random/uuid)
        dd if=$1 skip=$SECTOR count=$(expr $SIZE / 512) of="changeset/${SECTOR}.$UUID" 2> /dev/null
    fi
done < "tmpfifo"
