#!/bin/bash
set -e
rm -f changes
rm -f targetfile
rm -f tmpfifo
mkfifo tmpfifo

if [ -z $1 ] || [ -z $2 ]; then
    echo "hot-clone device targetfile"
    exit 1
fi

[ ! -e $1 ] && echo "device $1 does not exist" && exit 1

MINOR=$(stat -c %T $1)
MAJOR=$(stat -c %t $1)

echo "setup tracing"
./dump-changes $1 &
./trace-changes $MAJOR $MINOR > tmpfifo &

echo "copy device"
dd if=$1 of=$2 status=progress && kill %1
losetup /dev/loop1 $2

for FILE in $(ls -1t changeset/); do
    echo "Replay data from $FILE"
    SIZE=$(stat -c "%s" changeset/$FILE)
    SECTOR=$(echo $FILE | cut -d '.' -f 1)
    dd if=changeset/$FILE seek=$SECTOR count=$(expr $SIZE / 512) of=/dev/loop1 2>/dev/null
done

echo "comparing target and source"
md5sum /dev/loop0 /dev/loop1
losetup -d /dev/loop1
